version: "2.2.3"

services:
   #backend API
   face-recognition-api:
      container_name: backend
      build: ./
      command: npm start
      working_dir: /usr/src/face-recognition-api
      environment:
         POSTGRES_URI: postgres://sally:secret@postgres:5432/face-recognition-db
         REDIS_URI: redis://redis:6379

      ports:
         - "3000:3000"
      volumes:
         - ./:/usr/src/face-recognition-api
      networks:
         - redis

   #Postgres
   postgres:
      environment:
         POSTGRES_USER: sally
         POSTGRES_PASSWORD: secret
         POSTGRES_DB: face-recognition-db
         POSTGRES_HOST: postgres
      # container_name: postgres
      build: ./postgres
      ports:
         - "5432:5432"
      networks:
         - redis
   # psql postgres://sally:secret@localhost:5432/face-recognition-db

   # redis
   redis:
      image: redis
      networks:
         - redis
      ports:
         - "6379:6379"
networks:
   redis:
      driver: bridge
